version: "3.9"

services:
  whiteboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whiteboard-dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn app.main:asgi_app --host 0.0.0.0 --port 8000 --reload
